import { OnInit, EventEmitter } from '@angular/core';
export declare class NgxCustomDataTableComponent implements OnInit {
    radioSelectedValue: string;
    menus: any;
    uniqKey: string;
    autoGenerateId: boolean;
    keyOptional: boolean;
    showRadioInRows: boolean;
    showCheckBox: boolean;
    noActions: boolean;
    enableSelection: boolean;
    onlyDelete: boolean;
    sortOrder: number;
    sortKey: string;
    hideHeaderCheckBox: boolean;
    btnContents: any;
    noHeaderDropdown: boolean;
    selectionChange: any;
    tableList: any;
    tableKeysList: any;
    tableProfileList: any;
    selectedValueEmit: EventEmitter<any>;
    confirmAdd: EventEmitter<any>;
    confirmUpdate: EventEmitter<any>;
    selectedLinkEmit: EventEmitter<any>;
    confirmDelete: EventEmitter<any>;
    closeDialog: EventEmitter<any>;
    saveChoosenValues: EventEmitter<any>;
    selectInfoEmit: EventEmitter<any>;
    rowObj: {};
    editItems: any;
    clonedItems: any;
    items: any;
    itemObj: any;
    rowInx: string;
    addNewItems: any;
    newItem: string;
    choosenItems: any[];
    processes: any;
    profilesList: any;
    constructor();
    ngOnInit(): void;
    addNewItem(item?: any): void;
    filterDuplicates(item: any, key: any, keySet?: string): {}[];
    emailValidation(item?: any): boolean;
    dropdownValidation(item?: any): boolean;
    editCancel(uniqKey?: string): void;
    updateItem(item?: any): void;
    checkEmptyFields(item: any): boolean;
    removeRow(item: any): void;
    editRowItems(item?: any): void;
    deleteItem(id: string): void;
    getNextGroupId(): number;
    addNew(): void;
    selectValue(): void;
    selectInfo(set: any, item: any): void;
    selectLink(selectedItem?: any, $event?: any): void;
    saveItems(): void;
    cancelCheck(): void;
}
